### ISSUE TITLE
Allow grouping/tagging contacts

### ISSUE THREAD

**Issue by neutrinog** [neutrinog/prayerchart#8]
Groups should simply be labels with a customizable color associated with it. Each group will have it's own book mark.
When in the main list display groups as colored dots along the bottom of the contact except if that contact is bookmarked in the group the dot will show as a small colored bookmark.

- [x] write up new schema for tags
- [x] migrate the database to use the new schema
- [x] plan out ui for managing groups
- [ ] develop ui for groups

**Comment by neutrinog** [comment]
while we are updating the schema we should also begin storing the bookmarks in the database so that uninstalling and re-installing the app will maintain as much state as possible.
